# Generated by Django 4.1 on 2022-08-23 06:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('description_2', models.TextField()),
                ('birthday', models.DateField()),
                ('profile_img', models.ImageField(upload_to='profile/')),
                ('degree', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, choices=[('av', 'available'), ('nv', 'not available')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_strength', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='briefcase.bio')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='briefcase.skill')),
            ],
        ),
    ]
