# Generated by Django 4.1 on 2022-08-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='freelance',
            field=models.CharField(blank=True, choices=[('av', 'available'), ('nv', 'not available')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bio',
            name='city',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
