# Generated by Django 4.1 on 2022-08-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefcase', '0002_bio_freelance_alter_bio_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='degree',
            field=models.CharField(max_length=100),
        ),
    ]
