# Generated by Django 4.1 on 2022-08-25 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefcase', '0005_alter_bio_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterModelTable(
            name='bio',
            table='briefcase_bio',
        ),
    ]
