# Generated by Django 4.1 on 2022-08-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefcase', '0008_alter_bio_options_alter_employeeskills_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeskills',
            options={},
        ),
        migrations.AlterModelTable(
            name='employeeskills',
            table=None,
        ),
    ]
